# Generated by Django 5.1.4 on 2024-12-20 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('image1_main', models.ImageField(upload_to='room_images/')),
                ('image2', models.ImageField(upload_to='room_images/')),
                ('image3', models.ImageField(upload_to='room_images/')),
                ('image360', models.ImageField(upload_to='room_images/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtype_rooms', to='roomandsuites.roomtype')),
            ],
        ),
    ]
