# Generated by Django 5.1.4 on 2024-12-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomandsuites', '0003_alter_roomtype_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='room_type',
        ),
    ]
