# Generated by Django 5.1.4 on 2025-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomandsuites', '0004_rename_type_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image1_main',
            field=models.ImageField(upload_to='static/room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image2',
            field=models.ImageField(upload_to='static/room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image3',
            field=models.ImageField(upload_to='static/room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image360',
            field=models.ImageField(upload_to='static/room_images/'),
        ),
    ]
